### ISSUE TITLE
Why demo on Heroku?

### ISSUE THREAD

**Issue by rslvn** [lupas/nuxt-firebase-demo#38]
It does not work on firebase hosting? 
Why the demo is published on Heroku?

**Comment by lupas** [comment]
Hey @rslvn 

The aim of this repo is to **demo the nuxtjs/firebase module**, not to show how to deploy a Nuxt application on Firebase Functions/Hosting.

Since I wanted to show off the SSR feature of the module as well, I needed to deploy it as an universal (dynamic) app.

Firebase Hosting is straightforward when hosting a **static** website. It does **support dynamic hosting** as well through Firebase Functions, but that would make this demo unnecessarily complex since the demo is not about the deployment but about the module.

Hope that makes sense.

If you google "nuxt on firebase hosting" you'll find plenty of examples on how to deploy a Nuxt SSR app to Firebase.
